language: python
python: "2.7"
sudo: false

before_install:
  - pip install -U -r requirements.txt -r requirements-dev.txt
  - npm install

script:
  - flake8 .
  - npm test
  - py.test --cov-report=term --cov .

after_success:
  coveralls
